spring.application.name=JavaCodeWorking.HW.REST_API_Swagger

spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.operationsSorter=method

path.to.avatars.folder = avatars